name: tipsy_trove
description: Lets get drunk
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  dio: ^5.2.1+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  types:
    path: packages/types
  drinks_rest_api:
    path: packages/drinks_rest_api
  drinks_api:
    path: packages/drinks_api
  drinks_repository:
    path: packages/drinks_repository
  freezed_annotation: ^2.2.0
  ui_kit:
    path: packages/ui_kit


dev_dependencies:
  bloc_test: ^9.1.2
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.1
  mocktail_image_network: ^1.0.0
  very_good_analysis: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  freezed: ^2.3.5

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/config/
