name: tipsy_trove
description: Lets get drunk
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  dio: ^5.2.1+1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1

dev_dependencies:
  bloc_test: ^9.1.2
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
