name: drinks_rest_api
description: Actual REST API layer to fetch drinks
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dio: ^5.2.1+1
  drinks_api:
    path: ../drinks_api
  types:
    path: ../types

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0
