// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'drink_detail.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_DrinkDetail _$$_DrinkDetailFromJson(Map<String, dynamic> json) =>
    _$_DrinkDetail(
      id: json['idDrink'] as String?,
      drinkName: json['strDrink'] as String?,
      tags: json['strTags'] as String?,
      iba: json['strIBA'] as String?,
      alcoholType: json['strAlcoholic'] as String?,
      glass: json['strGlass'] as String?,
      instructions: json['strInstructions'] as String?,
      thumbnailUrl: json['strDrinkThumb'] as String?,
      ingredient1: json['ingredient1'] as String?,
      measure1: json['measure1'] as String?,
      ingredient2: json['ingredient2'] as String?,
      measure2: json['measure2'] as String?,
      ingredient3: json['ingredient3'] as String?,
      measure3: json['measure3'] as String?,
      ingredient4: json['ingredient4'] as String?,
      measure4: json['measure4'] as String?,
      ingredient5: json['ingredient5'] as String?,
      measure5: json['measure5'] as String?,
      ingredient6: json['ingredient6'] as String?,
      measure6: json['measure6'] as String?,
      ingredient7: json['ingredient7'] as String?,
      measure7: json['measure7'] as String?,
      ingredient8: json['ingredient8'] as String?,
      measure8: json['measure8'] as String?,
      ingredient9: json['ingredient9'] as String?,
      measure9: json['measure9'] as String?,
      ingredient10: json['ingredient10'] as String?,
      measure10: json['measure10'] as String?,
      ingredient11: json['ingredient11'] as String?,
      measure11: json['measure11'] as String?,
      ingredient12: json['ingredient12'] as String?,
      measure12: json['measure12'] as String?,
      ingredient13: json['ingredient13'] as String?,
      measure13: json['measure13'] as String?,
      ingredient14: json['ingredient14'] as String?,
      measure14: json['measure14'] as String?,
      ingredient15: json['ingredient15'] as String?,
      measure15: json['measure15'] as String?,
    );

Map<String, dynamic> _$$_DrinkDetailToJson(_$_DrinkDetail instance) =>
    <String, dynamic>{
      'idDrink': instance.id,
      'strDrink': instance.drinkName,
      'strTags': instance.tags,
      'strIBA': instance.iba,
      'strAlcoholic': instance.alcoholType,
      'strGlass': instance.glass,
      'strInstructions': instance.instructions,
      'strDrinkThumb': instance.thumbnailUrl,
      'ingredient1': instance.ingredient1,
      'measure1': instance.measure1,
      'ingredient2': instance.ingredient2,
      'measure2': instance.measure2,
      'ingredient3': instance.ingredient3,
      'measure3': instance.measure3,
      'ingredient4': instance.ingredient4,
      'measure4': instance.measure4,
      'ingredient5': instance.ingredient5,
      'measure5': instance.measure5,
      'ingredient6': instance.ingredient6,
      'measure6': instance.measure6,
      'ingredient7': instance.ingredient7,
      'measure7': instance.measure7,
      'ingredient8': instance.ingredient8,
      'measure8': instance.measure8,
      'ingredient9': instance.ingredient9,
      'measure9': instance.measure9,
      'ingredient10': instance.ingredient10,
      'measure10': instance.measure10,
      'ingredient11': instance.ingredient11,
      'measure11': instance.measure11,
      'ingredient12': instance.ingredient12,
      'measure12': instance.measure12,
      'ingredient13': instance.ingredient13,
      'measure13': instance.measure13,
      'ingredient14': instance.ingredient14,
      'measure14': instance.measure14,
      'ingredient15': instance.ingredient15,
      'measure15': instance.measure15,
    };
